### ISSUE TITLE
Eu me encaixo nessa turma ai?

### ISSUE THREAD

**Issue by lucasfrosty** [ifpb/egressos#45]
Tecnicamente eu nao sou egresso ja que nao terminei o curso, entao nao sei se eu posso colocar meu perfil ai ¯\_(ツ)_/¯
Posso fazer um PR anyway?

**Comment by luizchaves** [comment]
Estamos criando um outro portal para substituir esse que incluiria todos os alunos, e o egresso seria um filtro
